use cg;
select * from instructor;
select * from instructor where technologyname='java';
SET SQL_SAFE_UPDATES = 0;
update instructor set salary = (salary + 100) where instructortype = 'communication';
select instructortype, salary from instructor where instructortype='programming';
select instructortype, sum(salary) from instructor group by instructortype;
select * from instructor order by name;
select * from instructorinfo;
insert into instructorinfo values('1', 'rtdru', 1, 'dtrd@gmail', 906755564, 'english', 'spanish');
insert into instructorinfo values('2', 'bangalore', 2, 'dtuyuid@gmail', 906776544, 'english', 'hindi');
insert into instructorinfo values('3', 'chennai', 3, 'testrrd@gmail', 906755644, 'tamil', 'spanish');
insert into instructorinfo values('4', 'bangalore', 4, 'hgfrd@gmail', 90643244, 'hindi', 'english');
insert into instructorinfo values('5', 'mumbai', 5, 'uiytrd@gmail', 90677644, 'english', 'spanish');
insert into instructorinfo values('6', 'mumbai', 6, 'dtdsytrd@gmail', 9063244, 'spanish', 'english');
insert into instructorinfo values('7', 'chennai', 7, 'jhhiurd@gmail', 90656344, 'hindi', 'spanish');
insert into instructorinfo values('8', 'bangalore', 8, 'tufuytrd@gmail', 90445544, 'english', 'spanish');
insert into instructorinfo values('9', 'delhi', 9, 'uyfswrd@gmail', 90675554, 'english', 'spanish');
insert into instructorinfo values('10', 'delhi', 10, 'wawerd@gmail', 90633544, 'spanish', 'english');
insert into instructorinfo values('11', 'kolkata', 11, 'uiysdrd@gmail', 90672464, 'french', 'spanish');
insert into instructorinfo values('12', 'bangalore', 12, 'sdrtd@gmail', 906734544, 'spanish', 'kannada');
insert into instructorinfo values('13', 'mumbai', 13, 'duok@gmail', 90213544, 'english', 'french');
insert into instructorinfo values('14', 'kolkata', 14, 'erwd@gmail', 904534544, 'chinese', 'spanish');
insert into instructorinfo values('15', 'delhi', 15, 'uiguyrddtrd@gmail', 86575544, 'japanese', 'english');
insert into instructorinfo values('16', 'delhi', 16, 'rftydrtbvd@gmail', 342275544, 'english', 'latin');
insert into instructorinfo values('17', 'chennai', 17, 'tydertd@gmail', 233575544, 'spanish', 'latin');
insert into instructorinfo values('18', 'mumbai', 18, 'ghftrd@gmail', 97575544, 'chinese', 'english');
insert into instructorinfo values('19', 'kolkata', 19, 'hgfftd@gmail', 885675544, 'hindi', 'spanish');
insert into instructorinfo values('20', 'mumbai', 20, 'gftyd@gmail', 86675544, 'english', 'spanish');
select * from instructor inner join instructorinfo on instructor.instructorcode = instructorinfo.instructorcode where address = 'bangalore';
select * from instructor where technologyname like '%fsd%';
select name, instructor.instructorcode from instructor inner join instructorinfo on instructor.instructorcode = instructorinfo.instructorcode where firstlanguage='spanish';
select count(instructorcode) from instructorinfo where firstlanguage = 'spanish' OR secondlanguage='spanish';
update instructor inner join instructorinfo on instructor.instructorcode = instructorinfo.instructorcode set salary = (salary + 1000) where instructorinfo.firstlanguage='spanish' or instructorinfo.secondlanguage='spanish';
select * from instructor inner join instructorinfo on instructor.instructorcode = instructorinfo.instructorcode;
select instructor.instructorcode, jobstartyear, email, phone from instructor inner join instructorinfo on instructor.instructorcode = instructorinfo.instructorcode where firstlanguage='spanish';
alter table instructorinfo drop column secondlanguage;